DROP DATABASE IF EXISTS movie_info;
CREATE DATABASE movie_info;
USE `movie_info`;

-- --------------------------------------------------------

--
-- Table structure for table `movie`
--

CREATE TABLE `movie` (
  `_id` int(11) NOT NULL,
  `story` text CHARACTER SET utf8 DEFAULT NULL,
  `buy` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `video1` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `thumb` varchar(255) CHARACTER SET utf8 NOT NULL,
  `video2` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `poster` varchar(255) CHARACTER SET utf8 NOT NULL,
  `advice` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `title` varchar(255) CHARACTER SET utf8 NOT NULL,
  `cast` text CHARACTER SET utf8 DEFAULT NULL,
  `director` varchar(60) CHARACTER SET utf8 DEFAULT NULL,
  `genre` varchar(45) CHARACTER SET utf8 DEFAULT NULL,
  `duration` varchar(30) CHARACTER SET utf8 DEFAULT NULL,
  `release` varchar(30) CHARACTER SET utf8 DEFAULT NULL,
  `availability` varchar(15) CHARACTER SET utf8 NOT NULL,
  `longtitude` float(10,6) NOT NULL,
  `latitude` float(10,6) NOT NULL,
  `cinema` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `price` float(6,2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `movie`
--

INSERT INTO `movie` (`_id`, `story`, `buy`, `video1`, `thumb`, `video2`, `poster`, `advice`, `title`, `cast`, `director`, `genre`, `duration`, `release`, `availability`, `longtitude`, `latitude`, `cinema`, `price`) VALUES
(2,'The electrifying 1973 tennis match between World number one Billie Jean King (Emma Stone) and ex-champ and serial hustler Bobby Riggs (Steve Carell) was billed as THE BATTLE OF THE SEXES and became the most watched televised sports event of all time. The match caught the zeitgeist and sparked a global conversation on gender equality, spurring on the feminist movement.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=109 27 116 207 227 78 68 124 164 75 219 102 240 232 75 56','http://www.youtube.com/embed/WMdzBwsZRX8','images/movie/t-battleofthesexes-v2.jpg','http://www.youtube.com/embed/oLBHSuxwyuo','images/movie/m-battleofthesexes-v2.jpg','Some Mature Content','Battle Of The Sexes','Emma Stone, Steve Carell, Elisabeth Shue','Jonathan Dayton, Valerie Faris','Biography, Comedy, Sport','122 minutes','Thursday, 23 Nov 2017','Now Showing', 1.397118, 103.915634,'Shaw', 7.00),
(6,'Despite his family’s baffling generations-old ban on music, Miguel (voice of newcomer Anthony Gonzalez) dreams of becoming an accomplished musician like his idol, Ernesto de la Cruz (voice of Benjamin Bratt). Desperate to prove his talent, Miguel finds himself in the stunning and colorful Land of the Dead following a mysterious chain of events. Along the way, he meets charming trickster Hector (voice of Gael García Bernal), and together, they set off on an extraordinary journey to unlock the real story behind Miguel\'s family history.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=122 104 247 144 10 190 193 39 75 153 213 210 144 11 97 101','http://www.youtube.com/embed/OF9Ixfq4BCI','images/movie/t-coco-v3.jpg','http://www.youtube.com/embed/t1uM8yyKIUw','images/movie/m-coco-v3.jpg','Consumer Advice Not Available',"Disney / Pixar's Coco With Olaf`s Frozen Adventure",'Gael García Bernal, Anthony Gonzalez, Benjamin Bratt, Renée Victor','Lee Unkrich, Adrian Molina','Family','127 minutes','Thursday, 23 Nov 2017','Now Showing', 1.393771, 103.908783,'Golden Village', 6.00),
(7,'Fueled by his restored faith in humanity and inspired by Superman\'s selfless act, Bruce Wayne enlists the help of his newfound ally, Diana Prince, to face an even greater enemy. Together, Batman and Wonder Woman work quickly to find and recruit a team of metahumans to stand against this newly awakened threat. But despite the formation of this unprecedented league of heroes-Batman, Wonder Woman, Aquaman, Cyborg and The Flash-it may already be too late to save the planet from an assault of catastrophic proportions.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=186 59 253 53 14 219 210 221 83 240 193 168 219 73 205 215','http://www.youtube.com/embed/FlJCnOvTAFE','images/movie/t-justiceleague-v2.jpg','http://www.youtube.com/embed/gQexFxeThGQ','images/movie/m-justiceleague-v2.jpg','Some Violence','Justice League','Ben Affleck, Henry Cavill, Gal Gadot, Ezra Miller, Ray Fisher, Jason Momoa','Zack Snyder','Action, Adventure','120 minutes','Thursday, 16 Nov 2017','Now Showing', 0.000000, 0.000000,'Shaw', 5.00),
(8,'Marvel’s motormouth mercenary is back! Bigger, better and occasionally more pantless than ever before. When a super soldier arrives on a murderous mission, Deadpool is forced to think about friendship, family and what it really means to be a hero - all while kicking 50 shades of ass. Because, sometimes, to do the right thing you need to fight dirty.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=137 156 80 172 111 206 40 104 123 25 106 39 4 14 240 134','http://www.youtube.com/embed/F0FgeaLtAaU','images/movie/t-deadpool2.jpg','http://www.youtube.com/embed/IdagiO4fUSY','images/movie/m-deadpool2.jpg','Violence and Coarse Language','Deadpool 2','Josh Brolin, Morena Baccarin, Ryan Reynolds','David Leitch','Action, Adventure, Comedy','120 minutes','Thursday, 17 May 2018','Now Showing', 0.000000, 0.000000,'Shaw', 7.00),
(9,'In Marvel Studios\' \"Thor: Ragnarok\", Thor is imprisoned on the other side of the universe without his mighty hammer and finds himself in a race against time to get back to Asgard to stop Ragnarok- the destruction of his homeworld and the end of Asgardian civilization- the hands of an all-powerful new threat, the ruthless Hela. But first he must survive a deadly gladiatorial contest that pits him against his former ally and fellow Avenger- the Incredible Hulk!','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=154 83 226 57 227 111 57 245 173 47 178 217 190 185 254 7','http://www.youtube.com/embed/ue80QwXMRHg','images/movie/t-thorragnarok-v2.jpg','http://www.youtube.com/embed/lWyJRZRqLgM','images/movie/m-thorragnarok-v2.jpg','Some Violence',"Marvel's Thor: Ragnarok",'Chris Hemsworth, Tom Hiddleston, Cate Blanchett, Idris Elba, Jeff Goldblum, Tessa Thompson, Karl Urban, Mark Ruffalo, Anthony Hopkins','Taika Waititi','Action, Adventure','130 minutes','Thursday, 26 Oct 2017','Now Showing', 0.000000, 0.000000,'Shaw', 7.00),
(10,'A new dark force threatens Ponyville, and the Mane 6—Twilight Sparkle, Applejack, Rainbow Dash, Pinkie Pie, Fluttershy, and Rarity—embark on an unforgettable journey beyond Equestria where they meet new friends and exciting challenges on a quest to use the magic of friendship and save their home.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=211 2 147 52 246 80 150 32 76 154 203 221 195 94 169 165','http://www.youtube.com/embed/2o-AjlhI9mg','images/movie/t-mylittlepony.jpg','http://www.youtube.com/embed/1Amk3FzLS5k','images/movie/m-mylittlepony.jpg','Consumer Advice Not Available','My Little Pony: The Movie','Emily Blunt, Kristin Chenoweth, Liev Schreiber, Michael Peña, Sia, Taye Diggs, Uzo Aduba, Zoe Saldana','Jayson Thiessen','Animation','99 minutes','Thursday, 2 Nov 2017','Now Showing', 0.000000, 0.000000,'Shaw', 7.00),
(11,'In 1997, the financial crash, known in Thailand as the Tom Yum Goong Crisis, was a disastrous event that crept over Asia and left millionaires bankrupt overnight. A bright future which two best friends, Boum and Ib, pictured together fell apart when they found out that their families were going bankrupt. All of their assets were seized to satisfy their debts. The construction of a premium luxury condominium, which their parents jointly invested in, had been suspended. Unable to accept the harsh truth, they decided to end their lives together at the unfinished tower, where they promised to be together forever. In the end, Ib died all alone. Twenty years later, Boum (Numthip Jongrachatawiboon) becomes a successful real estate entrepreneur. One day, she gets to visit the abandoned tower with her beloved daughter, Bell (Apichaya Thongkham). That night, however, Boum wakes up and finds Bell sleepwalking and talking to herself in the dark. Bell’s sleepwalking condition continues to worsen every night. What concerns Boum the most is that Bell’s action and words in her sleepwalking state frighteningly remind Boum of Ib. What measures will Boum take to release herself from the promise that binds her? “Promise me you won’t leave me.”','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=169 245 237 149 101 39 1 104 207 103 57 129 221 228 83 23','http://www.youtube.com/embed/_M4xjmRA0XQ','images/movie/t-thepromise-thai.jpg','http://www.youtube.com/embed/gnwgMYeaqr4','images/movie/m-thepromise-thai.jpg','Horror','The Promise','Numthip Jongrachatawiboon, Apichaya Thongkham, Thunyaphat Pattarateerachaicharoen','Sophon Sakdaphisit','Horror','114 minutes','Thursday, 16 Nov 2017','Now Showing', 0.000000, 0.000000,'Shaw', 7.00),
(12,'Singapore\'s most successful movie franchise is back! After leaving the military, Lobang, Wayang King, Sergeant Ong, and Ken Chow are all busy with their respective career as civilians. That\'s until they are called back to serve the nation again under the Singapore Armed Forces\' Armoured Formation. Now they must juggle between work and their reservist duties. What hilarious situations will happen as they train together and their military roles are reversed? There\'ll be new enemy threats and their brotherhood will be put to the test.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=43 49 13 62 232 15 142 213 111 216 242 103 147 105 40 45','http://www.youtube.com/embed/h5FTv65A5ec','images/movie/t-abtm4.jpg','http://www.youtube.com/embed/Qiehhi2EI_0','images/movie/m-abtm4.jpg','Some Coarse Language','Ah Boys To Men 4','Tosh Zhang, Wang Weiliang, Joshua Tan, Maxi Lim, Noah Yap, Apple Chan','Jack Neo','Action, Comedy','133 minutes','Thursday, 9 Nov 2017','Now Showing', 0.000000, 0.000000,'Shaw', 7.00),
(13,'Directed by Marc Forster, this psychological drama defies genre to tell this obsessive love story. Gina (Blake Lively) & husband James (Jason Clarke) have an almost perfect marriage. After being blinded as a child in a nearly fatal car crash, Gina depends on James to feel and “see” the world around her, and it appears only to solidify their extremely passionate relationship. She envisions the world in her own vivid imagination with help from James\' descriptions. While the two enjoy a colorful existence living in Bangkok, their life and relationship are upended after Gina receives a corneal transplant & regains her sight. With her restored vision, Gina experiences the world with a new sense of wonder & independence which James finds threatening. It is only when Gina suddenly begins to lose her sight again that she finally realizes the disturbing reality of their marriage and their lives.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=172 237 127 248 73 122 12 18 40 121 249 162 224 153 147 8','http://www.youtube.com/embed/lJ1sCzPd9k8','images/movie/t-alliseeisyou.jpg','http://www.youtube.com/embed/67BpOpJDzfM','images/movie/m-AllISeeIsYou2017.jpg','Sexual Scenes','All I See Is You','Blake Lively, Jason Clarke, Ahna O\'Reilly, Yvonne Strahovski, Wes Chatham, Danny Huston','Marc Forster','Drama','110 minutes','Thursday, 16 Nov 2017','Now Showing', 0.000000, 0.000000,'Shaw', 7.00),
(14,'David (Julian Cheung) was drunk and lost control of his car to the opposite lane. The off-duty police officer, Sam (Louis Koo) and his wife Ah Si (Charmaine Sheh), were able to avoid the collision and kept safe by switching their steering wheel immediately. David’s car smashed Patrick’s car on the opposite lane eventually and Patrick was killed. Ms Xiao Hung, after breaking up with her boyfriend, committed suicide by jumping off a building and hit exactly on top of Patrick’s car.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=165 128 8 43 72 249 96 35 51 223 242 0 68 75 184 152','http://www.youtube.com/embed/KjxUpRHeNug','images/movie/t-alwaysbewithyou-2017.jpg','http://www.youtube.com/embed/ldcoK98XDV0','images/movie/m-alwaysbewithyou-2017.jpg','Violence And Disturbing Scenes','Always Be With You','Louis Koo, Julian Cheung, Charmaine Sheh, Gordon Lam, Charlene Choi','Herman Yau','Horror','98 minutes','Thursday, 2 Nov 2017','Now Showing', 0.000000, 0.000000,'Shaw', 7.00),
(15,'From the director of Beverly Hills Chihuahua, The Smurfs, and Scooby-Doo comes the latest family comedy SHOW DOGS! Starring Will Arnett, Chris Ludacris Bridges, Natasha Lyonne, Jordin Sparks, Gabriel Iglesias, Shaquille ONeal, Alan Cumming, and Stanley Tucci, SHOW DOGS tells the adventure of an unlikely pairing of a human detective (Arnett) and his canine partner (voice of Chris Ludacris Bridges), who has to go undercover at the worlds most exclusive dog show to solve his biggest case yet.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=79 86 186 198 38 45 213 165 80 158 235 130 2 87 160 67','http://www.youtube.com/embed/pUi0SnaG5dk','images/movie/t-showdogs2018.jpg','http://www.youtube.com/embed/gPwjNK5If48','images/movie/m-showdogs-2018.jpg','Consumer Advice Not Available','Show Dogs','Will Arnett, Natasha Lyonne, Ludacris, Stanley Tucci','Raja Gosnell','Comedy','93 minutes','Thursday, 24 May 2018','Now Showing', 0.000000, 0.000000,'Shaw', 7.00),
(17,'A father takes his son to tour colleges on the East Coast and meets up with an old friend who makes him feel inferior about his life\'s choices.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=27 145 168 74 144 52 50 253 246 105 106 100 45 236 252 64','http://www.youtube.com/embed/22w8T9K8iRU','images/movie/t-bradsstatus.jpg','http://www.youtube.com/embed/RAbt3OYhTtA','images/movie/m-bradsstatus-2017.jpg','Some Mature Content',"Brad's Status",'Ben Stiller, Jenna Fischer, Austin Abrams, Luke Wilson, Michael Sheen, Jemaine Clement','Mike White','Drama','102 minutes','Thursday, 2 Nov 2017','Now Showing', 0.000000, 0.000000,'Shaw', 7.00),
(18,'In 1963, illegal immigrant Ho (Donnie Yen) snuck into Hong Kong. Equipped with guts and combat skills, he plunged into the underground world. After many adversaries, the once good-natured man is physically crippled and transforms into a monster more atrocious than the most corrupted cops and ruthless drug dealers. Finally, Ho emerges as the most powerful Drug Lord under the control of the Chief Chinese Detective Sergeant, Lee Rock (Andy Lau). With the establishment of the Independent Commission Against Corruption (ICAC) in 1974, Rock is forced into premature retirement, but Ho still would not be stopped, as he is determined to become the sole dictator of the drug empire……','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=224 196 160 220 64 154 219 30 170 100 73 137 97 80 193 106','http://www.youtube.com/embed/7wO0XPT44i0','images/movie/t-chasingthedragon-v2.png','http://www.youtube.com/embed/O_bkhxx7bdE','images/movie/m-chasingthedragon-v2.png','Violence And Some Drug Use','Chasing The Dragon','Donnie Yen, Andy Lau','Wong Jing','Action, Crime, Thriller','128 minutes','Thursday, 5 Oct 2017','Now Showing', 0.000000, 0.000000,'Shaw', 7.00),
(19,'Blumhouse (Split, Get Out, Whiplash) produces an original and inventive rewinding thriller in Happy Death Day, in which a college student (Jessica Rothe, La La Land) relives the day of her murder with both its unexceptional details and terrifying end until she discovers her killer\'s identity.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=209 52 50 94 75 71 189 129 20 40 116 76 78 230 182 60','http://www.youtube.com/embed/wiPD9X43knU','images/movie/t-happydeathday.jpg','http://www.youtube.com/embed/1NTaDm3atkc','images/movie/m-happydeathday.jpg','Some Violence And Sexual References','Happy Death Day','Jessica Rothe, Israel Broussard, Ruby Modine, Charles Aitken, Laura Clifton','Christopher Landon','Thriller','96 minutes','Wednesday, 18 Oct 2017','Now Showing', 0.000000, 0.000000,'Shaw', 7.00),
(20,'Thirteen years ago on Halloween weekend – SAW and the character of JIGSAW introduced the world to a new face of horror. For seven straight years “If it’s Halloween it must be SAW” was a holiday tradition. After a series of murders bearing all the markings of the Jigsaw killer, law enforcement find themselves chasing the ghost of a man dead for over a decade and embroiled in a new game that’s only just begun. Is John Kramer back from the dead to remind the world to be grateful for the gift of life? Or is this a trap set by a killer with designs of their own?','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=5 29 18 103 192 142 7 247 110 36 246 71 203 48 235 80','http://www.youtube.com/embed/vPP6aIw1vgY','images/movie/t-jigsaw-2017.jpg','http://www.youtube.com/embed/i2yPP17Ing0','images/movie/m-jigsaw-2017.jpg','Violence And Gore','Jigsaw','Laura Vandervoot, Tobin Bell, Mandela Van Peebles, Matt Passmore','Michael Spierig, Peter Spierig','Horror, Thriller','92 minutes','Thursday, 2 Nov 2017','Now Showing', 0.000000, 0.000000,'Shaw', 7.00),
(21,'Suburbicon is a peaceful, idyllic suburban community with affordable homes and manicured lawns …the perfect place to raise a family, and in the summer of 1959, the Lodge family is doing just that. But the tranquil surface masks a disturbing reality, as husband and father Gardner Lodge (Matt Damon) must navigate the town’s dark underbelly of betrayal, deceit, and violence. This is a tale of very flawed people making very bad choices. This is Suburbicon.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=75 77 17 102 223 190 170 183 103 142 55 25 71 177 12 128','http://www.youtube.com/embed/cBezc1S1BAQ','images/movie/t-suburbicon-2017.jpg','http://www.youtube.com/embed/IYga2m0V2O0','images/movie/m-suburbicon-2017.jpg','Violence And Some Coarse Language','Suburbicon','George Clooney, Matt Damon, Oscar Issac, Julianne Moore, Josh Brolin','George Clooney','Comedy, Crime, Mystery','105 minutes','Thursday, 9 Nov 2017','Now Showing', 0.000000, 0.000000,'Shaw', 7.00),
(22,'The extraordinary true story of an unexpected friendship in the later years of Queen Victoria’s (Academy Award winner Judi Dench) remarkable rule. When Abdul Karim (Ali Fazal), a young clerk, travels from India to participate in the Queen’s Golden Jubilee, he is surprised to find favor with the Queen herself. As the Queen questions the constrictions of her long-held position, the two forge an unlikely and devoted alliance with a loyalty to one another that her household and inner circle all attempt to destroy. As the friendship deepens, the Queen begins to see a changing world through new eyes and joyfully reclaims her humanity.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=255 184 51 216 192 248 85 38 53 158 176 131 72 152 123 45','http://www.youtube.com/embed/BT2Ph_9bGPs','images/movie/t-victoriaandabdul-v2.jpg','http://www.youtube.com/embed/T504u17Ao9A','images/movie/m-victoriaandabdul-v2.jpg','Some Coarse Language','Victoria And Abdul','Judi Dench, Ali Fazal, Adeel Akhtar, Simon Callow, Michael Gambon, Eddie Izzard, Ruth McCabe, Tim Pigott-Smith, Julian Wadham, Olivia Williams','Stephen Frears','Comedy, Drama','112 minutes','Thursday, 9 Nov 2017','Now Showing', 0.000000, 0.000000,'Shaw', 7.00),
(24,'The sequel to the 2015 global smash, father and stepfather, Dusty (Mark Wahlberg) and Brad (Will Ferrell) have joined forces to provide their kids with the perfect Christmas. Their newfound partnership is put to the test when Dusty’s old-school, macho Dad (Mel Gibson) and Brad’s ultra-affectionate and emotional Dad (John Lithgow) arrive just in time to throw the holiday into complete chaos.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=240 114 157 208 10 95 218 124 177 58 175 114 48 14 69 216','http://www.youtube.com/embed/yyW_EX7iRW0','images/movie/t-daddyshome2-v2.jpg','http://www.youtube.com/embed/huaGQdrkrK0','images/movie/m-daddyshome2-v2.jpg','Some Sexual References',"Daddy's Home 2",'Will Ferrell, Mark Wahlberg, Linda Cardellini, John Cena,  John Lithgow & Mel Gibson','Sean Anders','Comedy, Family','100 minutes','Thursday, 30 Nov 2017','Coming Soon', 0.000000, 0.000000,'Shaw', 7.00),
(25,'What starts out as a lavish train ride through Europe quickly unfolds into one of the most stylish, suspenseful and thrilling mysteries ever told. From the novel by best-selling author Agatha Christie, \"Murder on the Orient Express\" tells the tale of thirteen strangers stranded on a train, where everyone\'s a suspect. One man must race against time to solve the puzzle before the murderer strikes again. Kenneth Branagh directs and leads an all-star cast including- Penelope Cruz, Willem Dafoe, Judi Dench, Johnny Depp, Michelle Pfeiffer, Daisy Ridley and Josh Gad.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=49 59 10 94 226 105 189 12 222 3 183 57 222 132 32 8','http://www.youtube.com/embed/KcdbyFzZHHY','images/movie/t-murderontheorientexpress-v2.jpg','http://www.youtube.com/embed/z68frP9Q7XA','images/movie/m-murderontheorientexpress-v2.jpg','Some Violence','Murder on the  Orient Express','Tom Bateman, Kenneth Branagh, Penelope Cruz, Willem Dafoe, Judi Dench, Johnny Depp, Josh Gad, Derek Jacobi, Leslie Odom Jr., Michelle Pfeiffer, Daisy Ridley, Marwan Kenzari, Olivia Colman, Lucy Boynton, Manuel Garcia-Rulfo, Sergei Polunin','Kenneth Branagh','Drama','114 minutes','Thursday, 30 Nov 2017','Coming Soon', 0.000000, 0.000000,'Shaw', 7.00),
(26,'Reckless police inspector Tung (Zhang Jin) is on a mission to crackdown on criminal Shing’s (Shawn Yue) gold smuggling scheme, yet fails to arrest him. As Tung continues his manhunt, he discovers Shing’s involvement with triad boss Blackie (Yasuaki Kurata), who hides on a casino cruise ship on the high seas.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=0 255 11 57 212 164 95 232 50 51 21 86 43 139 7 247','http://www.youtube.com/embed/3F81sPk0u4o','images/movie/t-thebrink.jpg','http://www.youtube.com/embed/z9SJxSXySSo','images/movie/m-thebrink2017.jpg','Violence','The Brink','Zhang Jin, Shawn Yue, Wu Yue, Lam Ka Tung, Janice Man','Jonathan Li','Action, Crime, Drama','100 minutes','Thursday, 30 Nov 2017','Coming Soon', 0.000000, 0.000000,'Shaw', 7.00),
(27,'The Man Who Invented Christmas tells the magical journey that led to the creation of Ebenezer Scrooge (Christopher Plummer), Tiny Tim and other classic characters from A Christmas Carol. Directed by Bharat Nalluri (Miss Pettigrew Lives for a Day), the film shows how Charles Dickens (Dan Stevens) mixed real life inspirations with his vivid imagination to conjure up unforgettable characters and a timeless tale, forever changing the holiday season into the celebration we know today.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=112 145 133 249 243 213 212 240 34 95 171 96 229 161 97 137','http://www.youtube.com/embed/nx3ctBjG6yI','images/movie/t-tmwic.jpg','http://www.youtube.com/embed/UxcnYR3mcPU','images/movie/m-tmwic.jpg','Consumer Advice Not Available','The Man Who Invented Christmas','Dan Stevens, Jonathan Pryce, Christopher Plummer','Bharat Nalluri','Biography, Comedy, Drama','104 minutes','Thursday, 30 Nov 2017','Coming Soon', 0.000000, 0.000000,'Shaw', 7.00),
(29,'The world’s favourite bear returns to the big screen in 2017. Happily settled with the Brown family in Windsor Gardens, Paddington has become a popular member of the community, spreading joy and marmalade wherever he goes. While searching for the perfect present for his beloved Aunt Lucy’s 100th birthday, Paddington spots a unique pop-up book in Mr Gruber’s antique shop, and embarks upon a series of odd jobs to buy it. But when the book is stolen, it’s up to Paddington and the Browns to unmask the thief...','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=63 172 75 33 231 236 37 121 252 102 206 137 203 18 241 222','http://www.youtube.com/embed/52x5HJ9H8DM','images/movie/t-paddington2-v2.jpg','http://www.youtube.com/embed/1XT-SQ2DPyk','images/movie/m-paddington2_2017.jpg','Consumer Advice Not Available','Paddington 2','Hugh Grant, Brendan Gleeson, Hugh Bonneville, Sally Hawkins, Julie Walters, Jim Broadbent, Peter Capaldi, Madeleine Harris, Samuel Joslin, Ben Whishaw, Imelda Staunton','Paul King','Animation, Comedy, Family','104 minutes','Thursday, 7 Dec 2017','Coming Soon', 0.000000, 0.000000,'Shaw', 7.00),
(31,'Michael Fassbender (X-Men series), Rebecca Ferguson (Mission: Impossible—Rogue Nation), Charlotte Gainsbourg (Independence Day: Resurgence), Val Kilmer (Heat) and Academy Award® winner J.K. Simmons (Whiplash) star in The Snowman, a terrifying thriller from director Tomas Alfredson (Let the Right One In, Tinker Tailor Soldier Spy), based on Jo Nesbø’s global bestseller. When an elite crime squad’s lead detective (Fassbender) investigates the disappearance of a victim on the first snow of winter, he fears an elusive serial killer may be active again. With the help of a brilliant recruit (Ferguson), the cop must connect decades-old cold cases to the brutal new one if he hopes to outwit this unthinkable evil before the next snowfall. The Snowman is produced by Working Title’s Tim Bevan and Eric Fellner (The Theory of Everything, Les Misérables), as well as Piodor Gustafsson and Robyn Slovo','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=211 0 93 222 156 214 11 58 191 232 122 212 164 50 69 142','http://www.youtube.com/embed/E8LttobzeQ4','images/movie/t-thesnowman-v2.jpg','http://www.youtube.com/embed/5A3THighARU','images/movie/m-thesnowman-v2.jpg','Consumer Advice Not Available','The Snowman','Michael Fassbender, Rebecca Ferguson, Charlotte Gainsbourg, Val Kilmer, J.K. Simmons','Thomas Alfredson','Thriller','N.A.','Thursday, 7 Dec 2017','Coming Soon', 0.000000, 0.000000,'Shaw', 7.00),
(32,'Based on the New York Times bestseller, WONDER tells the inspiring and heartwarming story of August Pullman. Born with facial differences that, up until now, have prevented him from going to a mainstream school, Auggie becomes the most unlikely of heroes when he enters the local fifth grade. As his family, his new classmates, and the larger community all struggle to find their compassion and acceptance, Auggie\'s extraordinary journey will unite them all and prove you can\'t blend in when you were born to stand out. Lionsgate presents, in association with Walden Media and Participant Media, a Mandeville Films / Lionsgate production.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=207 147 15 248 207 126 205 154 238 173 159 204 97 14 28 195','http://www.youtube.com/embed/ngiK1gQKgK8','images/movie/t-wonder-v2.jpg','http://www.youtube.com/embed/HZ46yR-Lo8c','images/movie/m-wonder(2).jpg','Consumer Advice Not Available','Wonder','Julia Roberts, Owen Wilson, Jacob Tremblay, Mandy Patinkin, Daveed Diggs','Stephen Chbosky','Family','114 minutes','Thursday, 14 Dec 2017','Coming Soon', 0.000000, 0.000000,'Shaw', 7.00),
(33,'Earth: One Amazing Day follows the journey of the sun for twenty four hours as it’s awesome power shapes the lives of all the animals on the amazing planet we call home. Even the most familiar species – ourselves. A breathtaking voyage across the continents and through the oceans and skies; Earth: One Amazing Day is an enchanting, big screen family friendly adventure that proves every day on Earth is heartwarming and inspiring.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=141 10 14 197 231 77 167 130 235 96 150 126 209 76 35 137','http://www.youtube.com/embed/LlmNg-27MrU','images/movie/t-earthoneamazingday.jpg','http://www.youtube.com/embed/ZbTbHNtYV_4','images/movie/m-earthoneamazingday.jpg','Consumer Advice Not Available','Earth: One Amazing Day','Robert Redford','Richard Dale, Lixin Fan, Peter Webber','Documentary','N.A.','Thursday, 21 Dec 2017','Coming Soon', 0.000000, 0.000000,'Shaw', 7.00),
(35,'\"Ferdinand\" tells the story of a giant bull with a big heart. After being mistaken for a dangerous beast, he is captured and torn from his home. Determined to return to his family, he rallies a misfit team on the ultimate adventure. Set in Spain, Ferdinand proves you can\'t judge a bull by its cover. From Blue Sky Studios and Carlos Saldanha, the director of \"Rio\" and inspired by the beloved book\"The Story of Ferdinand\" by Munro Leaf and Robert Lawson, \"Ferdinand\" is a heartwarming animated comedy adventure with an all-star cast that includes John Cena, Kate McKinnon, Gina Rodriguez, Anthony Anderson and many more.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=154 82 21 6 195 122 151 177 170 81 157 74 80 222 96 143','http://www.youtube.com/embed/KBofcN9NoVs','images/movie/t-ferdinand-v2.jpg','http://www.youtube.com/embed/n7RkOfN8KvE','images/movie/m-ferdinand-v2.jpg','Consumer Advice Not Available','Ferdinand','John Cena, Kate McKinnon, Gina Rodriguez, Daveed Diggs, Gabriel Iglesias, Bobby Cannavale, David Tennant, Anthony Anderson, Flula Borg, Sally Phillips, Boris Kodjoe, Jerrod Carmichael, Raul Esparza, Karla Martínez, Miguel Ángel Silvestre','Carlos Saldanha','Animation, Drama, Family','N.A.','Thursday, 21 Dec 2017','Coming Soon', 0.000000, 0.000000,'Shaw', 7.00),
(38,'Inspired by the imagination of P.T. Barnum, The Greatest Showman is an original musical that celebrates the birth of show business & tells of a visionary who rose from nothing to create a spectacle that became a worldwide sensation.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=112 151 165 141 40 179 93 200 210 27 29 42 104 38 27 58','http://www.youtube.com/embed/jr9QtXwC9vc','images/movie/t-thegreatestshowman-v2.jpg','http://www.youtube.com/embed/AXCTMGYUg9A','images/movie/m-thegreatestshowman-v2.jpg','Consumer Advice Not Available','The Greatest Showman','Hugh Jackman, Zac Efron, Michelle Williams, Rebecca Ferguson, Zendaya','Michael Gracey','Musical','105 minutes','Thursday, 28 Dec 2017','Coming Soon', 0.000000, 0.000000,'Shaw', 7.00),
(39,'During the early days of World War II, with the fall of France imminent, Britain faces its darkest hour as the threat of invasion looms. As the seemingly unstoppable Nazi forces advance, and with the Allied army cornered on the beaches of Dunkirk, the fate of Western Europe hangs on the leadership of the newly-appointed British Prime Minister Winston Churchill (Academy Award nominee Gary Oldman). While maneuvering his political rivals, he must confront the ultimate choice: negotiate with Hitler and save the British people at a terrible cost or rally the nation and fight on against incredible odds. Directed by Joe Wright, DARKEST HOUR is the dramatic and inspiring story of four weeks in 1940 during which Churchill’s courage to lead changed the course of world history.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=93 230 199 11 131 230 255 227 209 204 115 24 236 205 163 202','http://www.youtube.com/embed/2TwB_w83G1I','images/movie/t-darkesthour-v2.jpg','http://www.youtube.com/embed/4pNOCzV5jG0','images/movie/m-darkesthour-v2.jpg','Consumer Advice Not Available','Darkest Hour','Gary Oldman, Kristin Scott Thomas, Lily James, Stephen Dillane, Ben Mendelsohn','Joe Wright','Drama, Thriller','N.A.','Thursday, 4 Jan 2018','Coming Soon', 0.000000, 0.000000,'Shaw', 7.00),
(41,'When scientists discover how to shrink humans to five inches tall as a solution to over-population, Paul (Matt Damon) and his wife Audrey (Kristen Wiig) decide to abandon their stressed lives in order to get small and move to a new downsized community — a choice that triggers life-changing adventures.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=215 138 144 82 33 65 126 146 119 74 163 123 225 82 208 203','http://www.youtube.com/embed/UCrBICYM0yM','images/movie/t-downsizing.jpg','http://www.youtube.com/embed/0Md0XJZlbAk','images/movie/m-downsizing.jpg','Consumer Advice Not Available','Downsizing ','Matt Damon, Christoph Waltz, Hong Chau, Kristen Wiig','Alexander Payne','Comedy, Drama','N.A.','Thursday, 11 Jan 2018','Coming Soon', 0.000000, 0.000000,'Shaw', 7.00),
(42,'Taraji P. Henson is Mary, a hit woman working for an organized crime family in Boston, whose life is completely turned around when she meets a young boy whose path she crosses when a professional hit goes bad.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=108 226 38 8 169 21 64 146 110 209 59 143 137 100 135 62','http://www.youtube.com/embed/cUWKn4p2s_s','images/movie/t-proudmary.jpg','http://www.youtube.com/embed/FWQcAgQxiRI','images/movie/m-proudmary.jpg','Consumer Advice Not Available','Proud Mary','Taraji P. Henson, Billy Brown, Jahi Di\'Allo Winston, Danny Glover','Babak Najafi','Action, Adventure','N.A.','Thursday, 11 Jan 2018','Coming Soon', 0.000000, 0.000000,'Shaw', 7.00),
(44,'The story of a young boy in the Midwest is told simultaneously with a tale about a young girl in New York from fifty years ago as they both seek the same mysterious connection.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=67 171 111 1 8 199 230 208 175 180 201 230 85 242 185 68','http://www.youtube.com/embed/nu8X9ALV4fo','images/movie/t-wonderstruck.jpg','http://www.youtube.com/embed/Q8MUn9ddFzU','images/movie/m-wonderstruck.jpg','Consumer Advice Not Available','Wonderstruck','Amy Hargreaves, Michelle Williams, Julianne Moore','Todd Haynes','Drama','116 minutes','Thursday, 11 Jan 2018','Coming Soon', 0.000000, 0.000000,'Shaw', 7.00),
(45,'For his directorial debut, Andy Serkis brings to life the inspiring true love story between Robin and Diana Cavendish (Andrew Garfield, Claire Foy), an adventurous couple who refuse to give up in the face of a devastating disease. When Robin is struck down by polio at the age of 28, he is confined to a hospital bed and given only a few months to live. With the help of Diana\'s twin brothers (Tom Hollander) and the groundbreaking ideas of inventor Teddy Hall (Hugh Bonneville), Robin and Diana dare to escape the hospital ward to seek out a full and passionate life together — raising their young son, traveling and devoting their lives to helping other polio patients. Written by two-time Academy Award nominated writer William Nicholson, and shot by three-time Academy Award winner Robert Richardson, BREATHE is a heartwarming celebration of love and human possibility.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=56 102 252 160 116 132 168 223 56 157 241 32 151 102 224 77','http://www.youtube.com/embed/7_YnYrLfjxA','images/movie/t-breathe.jpg','http://www.youtube.com/embed/JycCFypvgmI','images/movie/m-breathe.jpg','Some Mature Content','Breathe','Andrew Garfield, Claire Foy, Hugh Bonneville, Tom Hollander','Andy Serkis','Drama','118 minutes','Thursday, 18 Jan 2018','Coming Soon', 0.000000, 0.000000,'Shaw', 7.00),
(46,'On 27th July 1890 a gaunt figure stumbled down a drowsy high street at twilight in the small French country town of Auvers.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=120 249 18 166 128 35 223 46 193 81 228 95 250 236 232 68','http://www.youtube.com/embed/CGzKnyhYDQI','images/movie/t-lovingvincent.jpg','http://www.youtube.com/embed/k8xcLdOjX6w','images/movie/m-lovingvincent.jpg','Sexual Scene','Loving Vincent','Robert Gulaczyk, Jerome Flynn, Aidan Turner, Eleanor Tomlinson','Dorota Kobiela and Hugh Welchman','Biography','95 minutes','Thursday, 18 Jan 2018','Coming Soon', 0.000000, 0.000000,'Shaw', 7.00),
(47,'In a superhero origin tale unlike any other, the film is the incredible true story of what inspired Harvard psychologist Dr. William Moulton Marston to create the iconic Wonder Woman character in the 1940\'s. While Marston\'s feminist superhero was criticized by censors for her \'sexual perversity\', he was keeping a secret that could have destroyed him. Marston’s muses for the Wonder Woman character were his wife Elizabeth Marston and their lover Olive Byrne, two empowered women who defied convention: working with Marston on human behavior research -- while building a hidden life with him that rivaled the greatest of superhero disguises.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=193 201 158 200 43 61 246 189 168 30 61 109 28 115 201 43','http://www.youtube.com/embed/r991pr4Fohk','images/movie/t-professormarston.jpg','http://www.youtube.com/embed/T4cMJ3rzdpI','images/movie/m-professormarston.jpg','Consumer Advice Not Available','Professor Marston  & The Wonder Women','Luke Evans, Rebecca Hall, Bella Heathcote, Connie Britton','Angela Robinson','Drama','N.A.','Thursday, 18 Jan 2018','Coming Soon', 0.000000, 0.000000,'Shaw', 7.00),
(48,'From master story teller, Guillermo del Toro, comes THE SHAPE OF WATER - an other-worldly fairy tale, set against the backdrop of Cold War era America circa 1963. In the hidden high-security government laboratory where she works, lonely Elisa (Sally Hawkins) is trapped in a life of silence and isolation. Elisa’s life is changed forever when she and co-worker Zelda (Octavia Spencer) discover a secret classified experiment.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=15 96 180 89 16 241 209 94 153 235 69 4 138 214 245 45','http://www.youtube.com/embed/uiA4B5Y63IQ','images/movie/t-theshapeofwater.jpg','http://www.youtube.com/embed/XFYWazblaUA','images/movie/m-theshapeofwater.jpg','Consumer Advice Not Available','The Shape Of Water','Sally Hawkins, Michael Shannon, Richard Jenkins, Doug Jones, Michael Stuhlbarg, Octavia Spencer','Guillermo del Toro','Drama','N.A.','Thursday, 18 Jan 2018','Coming Soon', 0.000000, 0.000000,'Shaw', 7.00),
(49,'In the epic finale to the Maze Runner saga, Thomas leads his group of escaped Gladers on their final and most dangerous mission yet. To save their friends, they must break into the legendary Last City, a WCKD-controlled labyrinth that may turn out to be the deadliest maze of all. Anyone who makes it out alive will get answers to the questions the Gladers have been asking since they first arrived in the maze.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=121 152 214 35 78 131 196 116 103 201 78 82 253 133 229 19','http://www.youtube.com/embed/S_9OSktlm6s','images/movie/t-mazerunnerthedeathcure.jpg','http://www.youtube.com/embed/Otu900mPT2c','images/movie/m-mazerunnerthedeathcure.jpg','Consumer Advice Not Available','Maze Runner: The Death Cure','Kaya Scodelario, Dylan O\'Brien, Walton Goggins','Wes Ball','Action, Adventure, Sci-Fi, Suspense, Thriller','N.A.','Thursday, 25 Jan 2018','Coming Soon', 0.000000, 0.000000,'Shaw', 7.00),
(51,'THREE BILLBOARDS OUTSIDE EBBING, MISSOURI is a darkly comedic drama from Academy Award® winner Martin McDonagh (IN BRUGES). After months have passed without a culprit in her daughter’s murder case, Mildred Hayes (Academy Award® winner Frances McDormand) makes a bold move, commissioning three signs leading into her town with a controversial message directed at William Willoughby (Academy Award® nominee Woody Harrelson), the town\'s revered chief of police. When his second-in-command Officer Dixon (Sam Rockwell), an immature mother’s boy with a penchant for violence, gets involved, the battle between Mildred and Ebbing\'s law enforcement is only exacerbated.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=148 92 240 163 119 123 182 115 160 16 223 47 98 112 40 2','http://www.youtube.com/embed/Jit3YhGx5pU','images/movie/t-threebillboards.jpg','http://www.youtube.com/embed/nefD7UOhLCo','images/movie/m-threebillboards.jpg','Consumer Advice Not Available','Three Billboards Outside Ebbing, Missouri','Frances McDormand, Sam Rockwell, Woody Harrelson, Abbie Cornish, John Hawkes, Lucas Hedges, Peter Dinklage','Martin McDonagh','Comedy, Drama','N.A.','Thursday, 25 Jan 2018','Coming Soon', 0.000000, 0.000000,'Shaw', 7.00),
(52,'Based on the unbelievable, but true events, I, TONYA is a darkly comedic tale of American figure skater, Tonya Harding, and one of the most sensational scandals in sports history. Though Harding was the first American woman to complete a triple axel in competition, her legacy was forever defined by her association with an infamous, ill-conceived, and even more poorly executed attack on fellow Olympic competitor Nancy Kerrigan. Featuring an iconic turn by Margot Robbie as the fiery Harding, a mustachioed Sebastian Stan as her impetuous ex-husband Jeff Gillooly, a tour-de-force performance from Allison Janney as her acid-tongued mother, LaVona Golden, and an original screenplay by Steven Rogers, Craig Gillespie’s I, TONYA is an absurd, irreverent, and piercing portrayal of Harding’s life and career in all of its unchecked - and checkered - glory.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=140 129 230 98 21 225 255 236 82 73 97 195 49 195 109 185','http://www.youtube.com/embed/KuDQOMICfr0','images/movie/t-itonya.jpg','http://www.youtube.com/embed/fbpWmvPGGws','images/movie/m-itonya.jpg','Consumer Advice Not Available','I,Tonya','Margot Robbie, Sebastian Stan, Allison Janney, Julianne Nicholson, Paul Walter Hauser, Bobby Cannavale','Craig Gillespie','Comedy','N.A.','Thursday, 1 Feb 2018','Coming Soon', 0.000000, 0.000000,'Shaw', 7.00),
(53,'Jamie Dornan and Dakota Johnson return as Christian Grey and Anastasia Steele in Fifty Shades Freed, the climactic chapter based on the worldwide bestselling “Fifty Shades” phenomenon. Bringing to a shocking conclusion events set in motion in 2015 and 2017’s blockbuster films that grossed almost $950 million globally, the film arrives for Valentine’s Day 2018.Believing they have left behind shadowy figures from their past, newlyweds Christian and Ana fully embrace an inextricable connection and shared life of luxury. But just as she steps into her role as Mrs. Grey and he relaxes into an unfamiliar stability, new threats could jeopardize their happy ending before it even begins.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=144 169 18 63 221 34 188 203 68 104 170 132 81 79 253 243','http://www.youtube.com/embed/nJCc5HRPxYA','images/movie/t-fiftyshadesfreed.jpg','http://www.youtube.com/embed/6dOxeQNUs7U','images/movie/m-fiftyshadesfreed.jpg','Consumer Advice Not Available','Fifty Shades Freed','Dakota Johnson, Jamie Dornan, Eric Johnson, Rita Ora, Luke Grimes, Victor Rasuk, Jennifer Ehle, Eloise Mumford, Max Martini, Callum Keith Rennie','James Foley','Drama','N.A.','Thursday, 8 Feb 2018','Coming Soon', 0.000000, 0.000000,'Shaw', 7.00),
(54,'Marvel Studios\' Black Panther follows T\'Challa who, after the death of his father, the King of Wakanda, returns home to the isolated, technologically advanced African nation to succeed to the throne and take his rightful place as king. But when a powerful old enemy reappears, T\'Challa\'s mettle as king -and Black Panther- is tested when he is drawn into a formidable conflict that puts the fate of Wakanda and the entire world at risk. Faced with treachery and danger, the young king must rally his allies and release the full power of Black Panther to defeat his foes and secure the safety of his people and their way of life.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=138 19 19 79 1 86 199 89 198 79 193 209 246 243 233 52','http://www.youtube.com/embed/dxWvtMOGAhw','images/movie/t-blackpanther.jpg','http://www.youtube.com/embed/xjDjIWPwcPU','images/movie/m-blackpanther.jpg','Consumer Advice Not Available','Marvel`s Black Panther','Chadwick Boseman, Michael B. Jordan, Lupita Nyong’o, Danai Gurira, Martin Freeman, Daniel Kaluuya, Letitia Wright, Winston Duke, Angela Bassett, Forest Whitaker, Andy Serkis','Ryan Coogler','Action, Adventure','N.A.','Thursday, 15 Feb 2018','Coming Soon', 0.000000, 0.000000,'Shaw', 7.00),
(55,'An epic adventure set in the last Ice Age. Europe, 20,000 years ago. While on his first hunt with his tribe’s most elite group, a young man is injured and left for dead. Awakening to find himself broken and alone -- he must learn to survive and navigate the harsh and unforgiving wilderness. Reluctantly taming a lone wolf abandoned by its pack, the pair learn to rely on each other and become unlikely allies, enduring countless dangers and overwhelming odds in order to find their way home before the deadly winter arrives.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=170 228 155 32 59 104 226 89 11 128 100 153 240 200 68 135','http://www.youtube.com/embed/Dq6Il_RmMRE','images/movie/t-alpha.jpg','http://www.youtube.com/embed/MU7YUQabmSE','images/movie/m-alpha.jpg','Consumer Advice Not Available','Alpha','Kodi Smit-McPhee, Jóhannes Haukur Johannesson','Albert Hughes','Action, Adventure','N.A.','Thursday, 1 Mar 2018','Coming Soon', 0.000000, 0.000000,'Shaw', 7.00),
(56,'Dominika Egorova is many things. A devoted daughter determined to protect her mother at all costs. A prima ballerina whose ferocity has pushed her body and mind to the absolute limit. A master of seductive and manipulative combat. When she suffers a career-ending injury, Dominika and her mother are facing a bleak and uncertain future. That is why she finds herself manipulated into becoming the newest recruit for Sparrow School, a secret intelligence service that trains exceptional young people like her to use their bodies and minds as weapons. After enduring the perverse and sadistic training process, she emerges as the most dangerous Sparrow the program has ever produced. Dominika must now reconcile the person she was with the power she now commands, with her own life and everyone she cares about at risk, including an American CIA agent who tries to convince her he is the only person she can trust.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=128 10 60 42 12 190 231 35 88 85 34 201 98 218 8 55','http://www.youtube.com/embed/ZQUBjoGm1ls','images/movie/t-redsparrow.jpg','http://www.youtube.com/embed/vVkZmff5KK8','images/movie/m-redsparrow.jpg','Consumer Advice Not Available','Red Sparrow','Jennifer Lawrence, Joel Edgerton, Matthias Schoenaerts, Charlotte Rampling, Mary-Louise Parker, Jeremy Irons','Francis Lawrence','Action, Adventure','N.A.','Thursday, 1 Mar 2018','Coming Soon', 0.000000, 0.000000,'Shaw', 7.00),
(57,'After the disappearance of her scientist father, three peculiar beings send Meg, her brother, and her friend to space in order to find him. Directed by Ava DuVernay from a screenplay by Jennifer Lee based upon the beloved novel by Madeleine L\'Engle, \"A Wrinkle in Time\" is produced by Jim Whitaker and Catherine Hand with Doug Merrifield serving as executive producer.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=186 181 208 102 49 220 136 172 36 212 18 99 196 116 186 232','http://www.youtube.com/embed/UhZ56rcWwRQ','images/movie/t-awrinkleintime.jpg','http://www.youtube.com/embed/E4U3TeY2wtM','images/movie/m-awrinkleintime.jpg','Consumer Advice Not Available','A Wrinkle In Time','Oprah Winfrey, Reese Witherspoon, Mindy Kaling, Guru Mbatha-Raw, Michael Pena, Levi Miller, Deric McCabe, André Holland, Rowan Blanchard, Zach Galifianakis, Chris Pine, Storm Reid','Ava DuVernay','Drama','N.A.','Thursday, 8 Mar 2018','Coming Soon', 0.000000, 0.000000,'Shaw', 7.00),
(58,'Dr. Paul Kersey (Bruce Willis) is a surgeon who only sees the aftermath of Chicago violence as it’s rushed into his ER – until his wife (Elisabeth Shue) and college-age daughter (Camila Morrone) are viciously attacked in their suburban home. With the police overloaded with crimes, Paul, burning for revenge, hunts for his family’s assailants to deliver justice. As the anonymous slayings of criminals grabs the media’s attention, the city wonders if this deadly vigilante is a guardian angel…or a grim reaper. Fury and fate collide in the intense, action-thriller Death Wish.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=56 19 182 69 12 132 76 253 172 199 149 34 166 242 177 193','http://www.youtube.com/embed/t4-Wa6cqWJo','images/movie/t-deathwish.jpg','http://www.youtube.com/embed/v_I4zqC7GN8','images/movie/m-deathwish.jpg','Violence And Some Coarse Language','Death Wish','Bruce Willis, Vincent D\'Onofrio, Elisabeth Shue, Camila Morrone, Dean Norris, Kimberly Elise','Eli Roth','Thriller','108 minutes','Thursday, 8 Mar 2018','Coming Soon', 0.000000, 0.000000,'Shaw', 7.00),
(59,'Peter Rabbit, the mischievous and adventurous hero who has captivated generations of readers, now takes on the starring role of his own irreverent, contemporary comedy with attitude. In the film, Peter\'s feud with Mr. McGregor (Domhnall Gleeson) escalates to greater heights than ever before as they rival for the affections of the warm-hearted animal lover who lives next door (Rose Byrne). James Corden voices the character of Peter with playful spirit and wild charm, with Margot Robbie, Elizabeth Debicki, and Daisy Ridley performing the voice roles of the triplets, Flopsy, Mopsy, and Cottontail.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=13 53 63 74 22 213 188 0 218 127 79 205 198 72 225 92','http://www.youtube.com/embed/c3ZlyIh9QZw','images/movie/t-peterrabbit.jpg','http://www.youtube.com/embed/bx5zeorHvdE','images/movie/m-peterrabbit.jpg','Consumer Advice Not Available','Peter Rabbit','Rose Byrne, Domhnall Gleeson, Sam Neill, Daisy Ridley, Elizabeth Debicki, Margot Robbie, James Corden','Will Gluck','Comedy','N.A.','Thursday, 8 Mar 2018','Coming Soon', 0.000000, 0.000000,'Shaw', 7.00);
INSERT INTO `movie` (`_id`, `story`, `buy`, `video1`, `thumb`, `video2`, `poster`, `advice`, `title`, `cast`, `director`, `genre`, `duration`, `release`, `availability`, `longtitude`, `latitude`, `cinema`, `price`) VALUES
(60,'Lara Croft, the fiercely independent daughter of a missing adventurer, must push herself beyond her limits when she finds herself on the island where her father disappeared. From Warner Bros. Pictures and Metro-Goldwyn-Mayer Pictures.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=203 251 225 202 230 102 183 255 232 219 193 212 232 43 115 224','http://www.youtube.com/embed/8ndhidEmUbI','images/movie/t-tombraider.jpg','http://www.youtube.com/embed/QKJ4CsZUWUo','images/movie/m-tombraider.jpg','Consumer Advice Not Available','Tomb Raider','Alicia Vikander, Dominic West, Walton Goggins, Daniel Wu','Roar Uthaug','Action, Adventure','N.A.','Thursday, 15 Mar 2018','Coming Soon', 0.000000, 0.000000,'Shaw', 7.00),
(61,'Join our favorite monster family as they embark on a vacation on a luxury monster cruise ship so Drac can take a summer vacation from providing everyone else\'s vacation at the hotel. It’s smooth sailing for Drac’s Pack as the monsters indulge in all of the shipboard fun the cruise has to offer, from monster volleyball to exotic excursions, and catching up on their moon tans. But the dream vacation turns into a nightmare when Mavis realizes Drac has fallen for the mysterious captain of the ship, Ericka, who hides a dangerous secret that could destroy all of monsterkind.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=36 100 192 228 165 122 41 39 86 30 186 229 133 177 147 162','http://www.youtube.com/embed/5TEylOMhZWw','images/movie/t-hoteltransylvania3monstervacation.jpg','http://www.youtube.com/embed/d5exSS74Lh0','images/movie/m-hoteltransylvania3monstervacation.jpg','Consumer Advice Not Available','Hotel Transylvania 3: Monster Vacation','Adam Sandler, Andy Samberg, Selena Gomez, Kevin James, David Spade, Steve Buscemi, Keegan-Michael Key, Molly Shannon, Fran Drescher, Mel Brooks','Genndy Tartakovsky','Family','N.A.','Thursday, 12 Jul 2018','Coming Soon', 0.000000, 0.000000,'Shaw', 7.00),
(62,'From filmmaker Steven Spielberg comes the science fiction action adventure “Ready Player One,” based on Ernest Cline’s bestseller of the same name, which has become a worldwide phenomenon.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=195 207 41 215 100 168 148 142 62 169 134 187 157 87 167 222','http://www.youtube.com/embed/cSp1dM2Vj48','images/movie/t-readyplayerone.jpg','http://www.youtube.com/embed/QrkOw3TzoA4','images/movie/m-readyplayerone.jpg','Some Violence and Coarse Language','Ready Player One','Mark Rylance, Simon Pegg, Tye Sheridan, Olivia Cooke, Ben Mendelsohn, T.J. Miller, Simon Pegg','Steven Spielberg','Action, Adventure, Sci-Fi','140 minutes','Thursday, 29 Mar 2018','Now Showing', 0.000000, 0.000000,'Shaw', 7.00),
(63,'Board the Millennium Falcon and journey to a galaxy far, far away in Solo: A Star Wars Story, an all-new adventure with the most beloved scoundrel in the galaxy. Through a series of daring escapades deep within a dark and dangerous criminal underworld, Han Solo befriends his mighty future copilot Chewbacca and meets the notorious gambler Lando Calrissian, in a journey that will set the course of one of the Star Wars sagas most unlikely heroes.','http://www.shaw.sg/sw_moviedetails.aspx?filmCode=121 178 214 196 66 143 4 117 191 163 54 189 23 130 101 100','http://www.youtube.com/embed/brb86yeVsqU','images/movie/t-solo(2).jpg','http://www.youtube.com/embed/KS_6mt9oviU','images/movie/m-solo(2).jpg','Some Violence','Solo: A Star Wars Story','Alden Ehrenreich, Woody Harrelson, Emilia Clarke, Donald Glover, Thandie Newton, Phoebe Waller-Bridge, Paul Bettany','Ron Howard','Action, Adventure, Sci-Fi','135 minutes','Thursday, 24 May 2018','Now Showing', 0.000000, 0.000000,'Shaw', 7.00);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `movie`
--
ALTER TABLE `movie`
  ADD PRIMARY KEY (`_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `movie`
--
ALTER TABLE `movie`
  MODIFY `_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=64;
